// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Jardineria_Gabriel.Models;

[Table("gama_producto")]
public partial class gama_producto
{
    [Key]
    [StringLength(50)]
    [Unicode(false)]
    public string gama { get; set; }

    [Unicode(false)]
    [Required]
    [MaxLength(50,ErrorMessage = "El máximo de carácteres es de 50")]
    [MinLength(10,ErrorMessage = "El mínimo de carácteres es de 10")]
    public string descripcion_texto { get; set; }

    [Unicode(false)]
    [MaxLength(50, ErrorMessage = "El máximo de carácteres es de 50")]
    [MinLength(10, ErrorMessage = "El mínimo de carácteres es de 10")]
    public string descripcion_html { get; set; }

    
    [Unicode(false)]
    [MaxLength(256, ErrorMessage = "El máximo de carácteres es de 256")]
    [MinLength(10, ErrorMessage = "El mínimo de carácteres es de 10")]
    public string imagen { get; set; }

    [InverseProperty("gamaNavigation")]
    public virtual ICollection<producto> productos { get; set; } = new List<producto>();
}