// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Discografia.Models;
using Microsoft.EntityFrameworkCore;

namespace Discografia.Data;

public partial class ChinookContext : DbContext
{
    public ChinookContext(DbContextOptions<ChinookContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Album> Albums { get; set; }

    public virtual DbSet<Artist> Artists { get; set; }

    public virtual DbSet<Track> Tracks { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Album>().ToTable("Album", t => t.ExcludeFromMigrations());
        modelBuilder.Entity<Artist>().ToTable("Artist", t => t.ExcludeFromMigrations());
        modelBuilder.Entity<Track>().ToTable("Track", t => t.ExcludeFromMigrations());
        modelBuilder.Entity<Album>(entity =>
        {
            entity.HasOne(d => d.Artist).WithMany(p => p.Albums).HasConstraintName("FK_AlbumArtistId");
        });
        modelBuilder.Entity<Review>().HasData(
            
            new Review 
            {
                Id = 1,
                Title= "Ta bueno",
                Description= "Re loco el concierto",
                Points = 4,
                ArtistId = 212,
            
            },
             new Review
             {
                 Id = 2,
                 Title = "Conierto",
                 Description = "Decepcionante",
                 Points = 1,
                 ArtistId = 155,

             }

            );
        modelBuilder.Entity<Track>(entity =>
        {
            entity.Property(e => e.TrackId).ValueGeneratedNever();

            entity.HasOne(d => d.Album).WithMany(p => p.Tracks)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_TrackAlbumId");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);

public DbSet<Discografia.Models.Review> Review { get; set; } = default!;
}