// <auto-generated />
using System;
using AUT02_05.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AUT02_05.Migrations.Diccionario
{
    [DbContext(typeof(DiccionarioContext))]
    partial class DiccionarioContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AUT02_05.Models.Espeng", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("esp")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ing")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("id")
                        .HasName("PK__Espeng__3213E83F72F14E7F");

                    b.ToTable("Espeng", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("AUT02_05.Models.Frase", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("EspengID")
                        .HasColumnType("int");

                    b.Property<string>("IdUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("fraesp")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("fraing")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.HasIndex("EspengID");

                    b.HasIndex("UserId");

                    b.ToTable("Frase", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            EspengID = 19489,
                            IdUser = "0",
                            fraesp = "\"Hicieron un zoom sobre la imagen para ver más detalles.\"",
                            fraing = "\"They zoomed in on the image to see more details.\""
                        },
                        new
                        {
                            id = 2,
                            EspengID = 19488,
                            IdUser = "0",
                            fraesp = "\"El zoólogo estaba observando el comportamiento de los elefantes.\"",
                            fraing = "\"The zoologist was observing the behavior of the elephants.\""
                        },
                        new
                        {
                            id = 3,
                            EspengID = 19485,
                            IdUser = "0",
                            fraesp = "\"Fuimos al zoo a ver a los leones y tigres.\"",
                            fraing = "\"We went to the zoo to see the lions and tigers.\""
                        },
                        new
                        {
                            id = 4,
                            EspengID = 19484,
                            IdUser = "0",
                            fraesp = "\"El área zonal tiene acceso directo a la autopista.\"",
                            fraing = "\"The zonal area has direct access to the highway.\""
                        },
                        new
                        {
                            id = 5,
                            EspengID = 5344,
                            IdUser = "0",
                            fraesp = "\"La cremallera de mi chaqueta está rota.\"",
                            fraing = "\"The zipper on my jacket is broken.\""
                        },
                        new
                        {
                            id = 6,
                            EspengID = 17156,
                            IdUser = "0",
                            fraesp = "\"Sión es una ciudad mencionada en muchos textos bíblicos.\"",
                            fraing = "\"Zion is a city mentioned in many biblical texts.\""
                        },
                        new
                        {
                            id = 7,
                            EspengID = 3743,
                            IdUser = "0",
                            fraesp = "\"El número cero es fundamental en matemáticas.\"",
                            fraing = "\"The number zero is fundamental in mathematics.\""
                        },
                        new
                        {
                            id = 8,
                            EspengID = 3626,
                            IdUser = "0",
                            fraesp = "\"La cebra tiene rayas blancas y negras.\"",
                            fraing = "\"The zebra has black and white stripes.\""
                        },
                        new
                        {
                            id = 9,
                            EspengID = 7557,
                            IdUser = "0",
                            fraesp = "\"Ella es una persona entusiasta que siempre apoya nuevos proyectos.\"",
                            fraing = "\"She is a zealous person who always supports new projects.\""
                        },
                        new
                        {
                            id = 10,
                            EspengID = 3650,
                            IdUser = "0",
                            fraesp = "\"El celota defendía su creencia con gran fervor.\"",
                            fraing = "\"The zealot defended his belief with great fervor.\""
                        },
                        new
                        {
                            id = 11,
                            EspengID = 5856,
                            IdUser = "0",
                            fraesp = "\"El defensor de los derechos humanos luchaba por la igualdad.\"",
                            fraing = "\"The zealot for human rights fought for equality.\""
                        },
                        new
                        {
                            id = 12,
                            EspengID = 3644,
                            IdUser = "0",
                            fraesp = "\"El celo por su trabajo le permitió lograr grandes éxitos.\"",
                            fraing = "\"His zeal for his work allowed him to achieve great successes.\""
                        },
                        new
                        {
                            id = 13,
                            EspengID = 19474,
                            IdUser = "0",
                            fraesp = "\"Me gusta zapear en las redes sociales para descubrir nuevas tendencias.\"",
                            fraing = "\"I like to zap (to) on social media to discover new trends.\""
                        },
                        new
                        {
                            id = 14,
                            EspengID = 8054,
                            IdUser = "0",
                            fraesp = "\"El estilo estrafalario de su ropa siempre llamaba la atención.\"",
                            fraing = "\"His zany style of clothing always attracted attention.\""
                        },
                        new
                        {
                            id = 15,
                            EspengID = 19459,
                            IdUser = "0",
                            fraesp = "\"Zagreb es la capital de Croacia.\"",
                            fraing = "\"Zagreb is the capital of Croatia.\""
                        },
                        new
                        {
                            id = 16,
                            EspengID = 19450,
                            IdUser = "0",
                            fraesp = "\"Yugoslavia fue un país que existió en el sureste de Europa.\"",
                            fraing = "\"Yugoslavia was a country that existed in Southeast Europe.\""
                        },
                        new
                        {
                            id = 17,
                            EspengID = 19451,
                            IdUser = "0",
                            fraesp = "\"El término yugoslavo se refiere a los pueblos de la antigua Yugoslavia.\"",
                            fraing = "\"The term Yugoslav refers to the peoples of the former Yugoslavia.\""
                        },
                        new
                        {
                            id = 18,
                            EspengID = 10645,
                            IdUser = "0",
                            fraesp = "\"Su actitud juvenil era refrescante y llena de energía.\"",
                            fraing = "\"His youthful attitude was refreshing and full of energy.\""
                        },
                        new
                        {
                            id = 19,
                            EspengID = 10646,
                            IdUser = "0",
                            fraesp = "\"La juventud tiene muchas ideas innovadoras que cambiarán el futuro.\"",
                            fraing = "\"Youth has many innovative ideas that will change the future.\""
                        },
                        new
                        {
                            id = 20,
                            EspengID = 17422,
                            IdUser = "0",
                            fraesp = "\"¿Dónde está tu libro?\"",
                            fraing = "\"Where is your book?\""
                        },
                        new
                        {
                            id = 21,
                            EspengID = 19498,
                            IdUser = "0",
                            fraesp = "\"Zúrich es conocida por su alto nivel de calidad de vida y su estabilidad económica.\"",
                            fraing = "\"Zurich is known for its high quality of life and economic stability.\""
                        },
                        new
                        {
                            id = 22,
                            EspengID = 19489,
                            IdUser = "0",
                            fraesp = "\"Usé el zoom para poder ver los detalles del cuadro con más claridad.\"",
                            fraing = "\"I used the zoom to get a clearer view of the details in the painting.\""
                        },
                        new
                        {
                            id = 23,
                            EspengID = 19486,
                            IdUser = "0",
                            fraesp = "\"En la universidad",
                            fraing = " estudié zoología porque siempre me han fascinado los animales.\""
                        },
                        new
                        {
                            id = 24,
                            EspengID = 19488,
                            IdUser = "0",
                            fraesp = "\"El zoólogo recogió datos durante su investigación sobre los gorilas.\"",
                            fraing = "\"The zoologist gathered data during his research on gorillas.\""
                        },
                        new
                        {
                            id = 25,
                            EspengID = 19487,
                            IdUser = "0",
                            fraesp = "\"El zoológico tiene una nueva exposición de aves exóticas.\"",
                            fraing = "\"The zoological park has a new exhibit of exotic birds.\""
                        },
                        new
                        {
                            id = 26,
                            EspengID = 19485,
                            IdUser = "0",
                            fraesp = "\"Los niños se divierten mucho viendo a los animales en el zoo.\"",
                            fraing = "\"The kids have a lot of fun watching the animals at the zoo.\""
                        },
                        new
                        {
                            id = 27,
                            EspengID = 19483,
                            IdUser = "0",
                            fraesp = "\"La zona residencial está muy tranquila",
                            fraing = " ideal para vivir.\""
                        },
                        new
                        {
                            id = 28,
                            EspengID = 19484,
                            IdUser = "0",
                            fraesp = "\"La zona de estacionamiento es exclusiva para empleados.\"",
                            fraing = "\"The parking zone is reserved for employees.\""
                        },
                        new
                        {
                            id = 29,
                            EspengID = 19481,
                            IdUser = "0",
                            fraesp = "\"El zodíaco chino se basa en un ciclo de 12 años.\"",
                            fraing = "\"The Chinese zodiac is based on a 12-year cycle.\""
                        },
                        new
                        {
                            id = 30,
                            EspengID = 5344,
                            IdUser = "0",
                            fraesp = "\"La cremallera de mi mochila se rompió cuando la cerré demasiado rápido.\"",
                            fraing = "\"The zipper on my backpack broke when I zipped it up too quickly.\""
                        },
                        new
                        {
                            id = 31,
                            EspengID = 17001,
                            IdUser = "0",
                            fraesp = "\"Escuché un silbido extraño que provenía del pasillo.\"",
                            fraing = "\"I heard a strange whistle coming from the hallway.\""
                        },
                        new
                        {
                            id = 32,
                            EspengID = 17156,
                            IdUser = "0",
                            fraesp = "\"Sión fue un símbolo importante en las escrituras religiosas.\"",
                            fraing = "\"Zion was an important symbol in religious scriptures.\""
                        },
                        new
                        {
                            id = 33,
                            EspengID = 1241,
                            IdUser = "0",
                            fraesp = "\"Esa película tiene un estilo animado que atrae tanto a niños como a adultos.\"",
                            fraing = "\"That movie has a zestful style that appeals to both children and adults.\""
                        },
                        new
                        {
                            id = 34,
                            EspengID = 3743,
                            IdUser = "0",
                            fraesp = "\"El número cero tiene un valor único en matemáticas y ciencias.\"",
                            fraing = "\"The number zero has a unique value in mathematics and science.\""
                        },
                        new
                        {
                            id = 35,
                            EspengID = 3670,
                            IdUser = "0",
                            fraesp = "\"Alcanzaron el cenit de su éxito cuando su álbum llegó al número uno.\"",
                            fraing = "\"They reached the zenith of their success when their album hit number one.\""
                        },
                        new
                        {
                            id = 36,
                            EspengID = 3626,
                            IdUser = "0",
                            fraesp = "\"En el safari",
                            fraing = " vimos una cebra cruzando la carretera.\""
                        },
                        new
                        {
                            id = 37,
                            EspengID = 3649,
                            IdUser = "0",
                            fraesp = "\"Es muy celoso con sus pertenencias",
                            fraing = " no le gusta compartir.\""
                        },
                        new
                        {
                            id = 38,
                            EspengID = 7557,
                            IdUser = "0",
                            fraesp = "\"Es una persona tan entusiasta que contagia su energía a los demás.\"",
                            fraing = "\"She is such a zealous person that she spreads her energy to others.\""
                        },
                        new
                        {
                            id = 39,
                            EspengID = 8282,
                            IdUser = "0",
                            fraesp = "\"El fanatismo religioso puede ser peligroso si se lleva al extremo.\"",
                            fraing = "\"Religious zealotry can be dangerous if taken to the extreme.\""
                        },
                        new
                        {
                            id = 40,
                            EspengID = 3650,
                            IdUser = "0",
                            fraesp = "\"El celota estaba dispuesto a dar su vida por su causa.\"",
                            fraing = "\"The zealot was willing to give his life for his cause.\""
                        },
                        new
                        {
                            id = 41,
                            EspengID = 5856,
                            IdUser = "0",
                            fraesp = "\"El defensor de los derechos civiles luchó por la igualdad en la sociedad.\"",
                            fraing = "\"The zealot for civil rights fought for equality in society.\""
                        },
                        new
                        {
                            id = 42,
                            EspengID = 3644,
                            IdUser = "0",
                            fraesp = "\"Su celo por la excelencia lo ha llevado a ser un líder en su campo.\"",
                            fraing = "\"His zeal for excellence has made him a leader in his field.\""
                        },
                        new
                        {
                            id = 43,
                            EspengID = 19474,
                            IdUser = "0",
                            fraesp = "\"Me encanta zapear entre canales hasta encontrar algo interesante.\"",
                            fraing = "\"I love zapping between channels until I find something interesting.\""
                        },
                        new
                        {
                            id = 44,
                            EspengID = 8054,
                            IdUser = "0",
                            fraesp = "\"Su comportamiento estrafalario lo hizo famoso en la escuela.\"",
                            fraing = "\"His zany behavior made him famous at school.\""
                        },
                        new
                        {
                            id = 45,
                            EspengID = 19459,
                            IdUser = "0",
                            fraesp = "\"Zagreb es una ciudad vibrante con mucha historia y cultura.\"",
                            fraing = "\"Zagreb is a vibrant city with a lot of history and culture.\""
                        },
                        new
                        {
                            id = 46,
                            EspengID = 19450,
                            IdUser = "0",
                            fraesp = "\"Yugoslavia fue un país que dejó una huella importante en la historia de Europa.\"",
                            fraing = "\"Yugoslavia was a country that left a significant mark on European history.\""
                        },
                        new
                        {
                            id = 47,
                            EspengID = 19451,
                            IdUser = "0",
                            fraesp = "\"La comida yugoslava es muy variada y deliciosa",
                            fraing = " con influencias balcánicas.\""
                        },
                        new
                        {
                            id = 48,
                            EspengID = 10645,
                            IdUser = "0",
                            fraesp = "\"Su personalidad juvenil siempre traía una energía renovadora al grupo.\"",
                            fraing = "\"His youthful personality always brought a refreshing energy to the group.\""
                        },
                        new
                        {
                            id = 49,
                            EspengID = 10646,
                            IdUser = "0",
                            fraesp = "\"La juventud de hoy está más conectada globalmente que nunca antes.\"",
                            fraing = "\"Today's youth is more globally connected than ever before.\""
                        },
                        new
                        {
                            id = 50,
                            EspengID = 17422,
                            IdUser = "0",
                            fraesp = "\"Tu respuesta no me parece correcta",
                            fraing = " ¿puedes explicar más?\""
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IdentityUser", (string)null);
                });

            modelBuilder.Entity("AUT02_05.Models.Frase", b =>
                {
                    b.HasOne("AUT02_05.Models.Espeng", "Espeng")
                        .WithMany("frase")
                        .HasForeignKey("EspengID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Espeng");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AUT02_05.Models.Espeng", b =>
                {
                    b.Navigation("frase");
                });
#pragma warning restore 612, 618
        }
    }
}
