// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AUT02_05.Models;

[Table("Espeng")]
public partial class Espeng
{
    [Key]
    public int id { get; set; }

    [DisplayName("Español")]
    [StringLength(50)]
    [Unicode(false)]
    public string esp { get; set; }

    [DisplayName("Ingles")]
    [StringLength(50)]
    [Unicode(false)]
    public string ing { get; set; }
    public List<Frase> frase { get; set; }
}