// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using AUT02_05.Models;
using Microsoft.CodeAnalysis.Elfie.Serialization;
using Microsoft.EntityFrameworkCore;

namespace AUT02_05.Data;

public partial class DiccionarioContext : DbContext
{
    public DiccionarioContext()
    {
    }

    public DiccionarioContext(DbContextOptions<DiccionarioContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Espeng> Espengs { get; set; }



    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Espeng>().ToTable(t => t.ExcludeFromMigrations());
        
            List<Frase> examples = new List<Frase>();
            string linea;
            string[] tLinea;
            int i = 1;
            using (StreamReader sr = new(new FileStream("ejemplos.csv", FileMode.Open, FileAccess.Read)))
                while (!String.IsNullOrWhiteSpace(linea = sr.ReadLine()))
                {
                    try
                    {
                        tLinea = linea.Split(",");
                        examples.Add(new Frase { id = i, EspengID = Int32.Parse(tLinea[0]), fraesp = tLinea[1], fraing = tLinea[2], IdUser = "0" });
                    }
                    catch (Exception exception)
                    {
                        Console.WriteLine(exception.Message);
                    }
                    i++;
                }
            modelBuilder.Entity<Frase>().HasData(examples.ToList());
        

        modelBuilder.Entity<Espeng>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Espeng__3213E83F72F14E7F");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);

public DbSet<AUT02_05.Models.Frase> Frase { get; set; } = default!;
}